fix(ci): Ensure workflows are fails when tests fail.

diff --git a/.github/workflows/test-apps.yml b/.github/workflows/test-apps.yml
--- a/.github/workflows/test-apps.yml
+++ b/.github/workflows/test-apps.yml
@@ -32,11 +32,26 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-go-${{ matrix.go-version }}-
 
-      - name: Run tests for all pkg modules
+      - name: Run tests for all services
         run: |
           set -e
-          find ./apps -type f -name "go.mod" -execdir sh -c '
-            dir=$(dirname "{}")
+          FAILED=0
+
+          for modfile in $(find ./apps -type f -name "go.mod"); do
+            dir=$(dirname "$modfile")
             echo "Running tests in $dir"
-            (cd "$dir" && go mod download && go test ./...)
-          ' \;
+            (
+              cd "$dir"
+              go mod download
+              go test ./...
+            ) || {
+              echo "Tests failed in $dir"
+              FAILED=1
+            }
+          done
+
+          if [ "$FAILED" -ne 0 ]; then
+            echo "Some tests failed"
+            exit 1
+          fi
+
diff --git a/.github/workflows/test-pkg.yaml b/.github/workflows/test-pkg.yaml
--- a/.github/workflows/test-pkg.yaml
+++ b/.github/workflows/test-pkg.yaml
@@ -36,8 +36,22 @@ jobs:
       - name: Run tests for all pkg modules
         run: |
           set -e
-          find ./pkg -type f -name "go.mod" -execdir sh -c '
-            dir=$(dirname "{}")
+          FAILED=0
+
+          for modfile in $(find ./pkg -type f -name "go.mod"); do
+            dir=$(dirname "$modfile")
             echo "Running tests in $dir"
-            (cd "$dir" && go mod download && go test ./...)
-          ' \;
+            (
+              cd "$dir"
+              go mod download
+              go test ./...
+            ) || {
+              echo "Tests failed in $dir"
+              FAILED=1
+            }
+          done
+
+          if [ "$FAILED" -ne 0 ]; then
+            echo "Some tests failed"
+            exit 1
+          fi
